---
version: '3'
services:

  freqtrade:
    #image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    #build:
    #  context: .
    #  dockerfile: "./docker/Dockerfile.matplotlib"
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    #  --strategy MagicBuyStrategy
    # --config /freqtrade/user_data/config_telegram.json
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/Test3Strategy.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config_secret.json
      --strategy Test3Strategy


  freqtrade2:
    #image: freqtradeorg/freqtrade:stable
    #image: freqtradeorg/freqtrade:develop
    # Use plotting image
    image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    #build:
    #  context: .
    #  dockerfile: "./docker/Dockerfile.matplotlib"
    restart: unless-stopped
    container_name: freqtrade2
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8081 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8081:8080"
    # Default command used when running `docker compose up`
    # --config /freqtrade/user_data/config_telegram.json
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade2.log
      --db-url sqlite:////freqtrade/user_data/Test4Strategy.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/config_secret.json
      --strategy Test4Strategy
